networks:
  ai_network:
    driver: bridge

services:
  heygem-web:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: heygem-web
    restart: always
    ports:
      - '8090:8090'
    volumes:
      - ~/heygem_data/voice/data:/root/heygem_data/voice/data
      - ~/heygem_data/face2face:/root/heygem_data/face2face
      - ~/heygem_data/face2face/result:/root/heygem_data/face2face/result
      - ${COMPANY_DIR:-./company}:/mnt/c/company
      - ./client/dist:/root/client/dist
    environment:
      - APP_PORT=8090
      - HOST_VOICE_DIR=/root/heygem_data/voice/data
      - HOST_VIDEO_DIR=/root/heygem_data/face2face
      - HOST_RESULT_DIR=/root/heygem_data/face2face/result
      - WIN_COMPANY_DIR=/mnt/c/company
      - TTS_BASE_URL=http://heygem-tts:8080
      - VIDEO_BASE_URL=http://heygem-gen-video:8383
      - GEN_VIDEO_CONTAINER=heygem-gen-video
      - GEN_VIDEO_CONTAINER_DATA_ROOT=/code/data
      - STATIC_DIR=/root/client/dist
    depends_on:
      - heygem-tts
      - heygem-gen-video
    networks:
      - ai_network
  heygem-tts:
    image: guiji2025/fish-speech-ziming
    container_name: heygem-tts
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
    ports:
      - '18180:8080'
    volumes:
      - ~/heygem_data/voice/data:/code/data
    command: /bin/bash -c "/opt/conda/envs/python310/bin/python3 tools/api_server.py --listen 0.0.0.0:8080"
    networks:
      - ai_network
  heygem-asr:
    image: guiji2025/fun-asr
    container_name: heygem-asr
    restart: always
    runtime: nvidia
    privileged: true
    working_dir: /workspace/FunASR/runtime
    ports:
      - '10095:10095'
    command: sh /run.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ai_network
  heygem-gen-video:
    image: guiji2025/heygem.ai
    container_name: heygem-gen-video
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - ~/heygem_data/face2face:/code/data
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: '8g'
    ports:
      - '8383:8383'
    command: python /code/app_local.py
    networks:
      - ai_network
