networks:
  ai_network:
    driver: bridge

services:
  heygem-web:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: heygem-web
    restart: always
    ports:
      - '8090:8090'
    volumes:
      - /mnt/windows-digitalpeople:/mnt/windows-digitalpeople
      - ./client/dist:/root/client/dist
      # 使用仓库内的 users.json 覆盖默认用户配置
      - ./server/data/users.json:/root/data/users.json:ro
    environment:
      - APP_PORT=8090
      - STATIC_DIR=/root/client/dist
    depends_on:
      - heygem-tts
      - heygem-gen-video
    networks:
      - ai_network
  heygem-tts:
    image: guiji2025/fish-speech-ziming
    container_name: heygem-tts
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
    ports:
      - '18180:8080'
    volumes:
      - /mnt/windows-digitalpeople/voice/data:/code/data
    command: /bin/bash -c "/opt/conda/envs/python310/bin/python3 tools/api_server.py --listen 0.0.0.0:8080"
    networks:
      - ai_network
  heygem-asr:
    image: guiji2025/fun-asr
    container_name: heygem-asr
    restart: always
    runtime: nvidia
    privileged: true
    working_dir: /workspace/FunASR/runtime
    ports:
      - '10095:10095'
    command: sh /run.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ai_network
  heygem-gen-video:
    image: guiji2025/heygem.ai
    container_name: heygem-gen-video
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - /mnt/windows-digitalpeople/face2face:/code/data
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: '8g'
    ports:
      - '8383:8383'
    command: python /code/app_local.py
    networks:
      - ai_network
