version: '3.8'
services:
  heygem-helper:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: heygem-helper:latest
    container_name: heygem-helper
    environment:
      - APP_PORT=8090
      - STATIC_DIR=/app/client-dist
    volumes:
      - /mnt/windows-digitalpeople:/mnt/windows-digitalpeople
      - /var/run/docker.sock:/var/run/docker.sock
      - ./client/dist:/app/client-dist:ro
    ports:
      - "8090:8090"
